### ISSUE TITLE
HAR (Chrome) for https://www.verizonwireless.com/devices breaks PageXray

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/pagexray#56]
Reported in https://github.com/sitespeedio/sitespeed.io/issues/1906

```
TypeError: Cannot read property 'response' of undefined
    at har.log.entries.forEach.entry (/Users/phedenskog/git/pagexray/lib/index.js:98:41)
    at Array.forEach (<anonymous>)
    at Object.convert (/Users/phedenskog/git/pagexray/lib/index.js:84:21)
```

**Comment by soulgalore** [comment]
That page redirects like this:
https://www.verizonwireless.com/devices -> http://www.verizonwireless.com/devices -> https://www.verizonwireless.com/devices but actually set the protocol as HTTPS (instead of lowercase) and right now we are case sensitive.

**Comment by soulgalore** [comment]
fixed
